# Generated by Django 3.1.3 on 2020-11-07 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('termsandconditions', '0003_auto_20170627_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='date_active',
            field=models.DateTimeField(blank=True, help_text='Leave Null To Never Make Active', null=True, verbose_name='date active'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='info',
            field=models.TextField(blank=True, default='', help_text="Provide users with some info about what's changed and why", verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='name',
            field=models.TextField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='version_number',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='version number'),
        ),
        migrations.AlterField(
            model_name='usertermsandconditions',
            name='terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userterms', to='termsandconditions.termsandconditions', verbose_name='terms'),
        ),
        migrations.AlterField(
            model_name='usertermsandconditions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userterms', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
