# This workflow uses UV to upload a new package version when a release is created.

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      with:
        python-version: '3.13'
    - name: Build and publish
      run: |
        uv build
        uv publish
