# This workflow uses UV to upload a new package version when a release is created.

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade uv
        uv install setuptools wheel
    - name: Build and publish
      env:
        UV_PUBLISH_USERNAME: ${{ secrets.PYPI_USERNAME }}
        UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        uv build
        uv publish
